katalog/urls.py
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),

]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import create_task
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import delete_task
from todolist.views import delete_task_ajax
from todolist.views import status
from todolist.views import status_ajax
from todolist.views import show_todolist_ajax
from todolist.views import get_todolist_json
from todolist.views import show_json
from todolist.views import submit_ajax
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('html/', show_todolist, name='show_todolist'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
    path('html/', show_todolist_ajax, name='show_todolist_ajax'),
    path('html/create-task/', create_task, name='create_task'),
    path('create-task/', create_task, name='create_task'),
    path('data-status/<int:id>', status, name='status'),
    path('html/data-status/<int:id>', status, name='status'),
    path('html/ajax/data-status/<int:id>', status, name='status'),
    path('ajax/data-status-ajax/<int:id>', status_ajax, name='status_ajax'),
    path('html/data-status-ajax/<int:id>', status_ajax, name='status_ajax'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('html/delete-task/<int:id>', delete_task, name='delete_task'),
    path('html/ajax/delete-task-ajax/<int:id>', delete_task_ajax, name='delete_task_ajax'),
    path('ajax/delete-task-ajax/<int:id>', delete_task_ajax, name='delete_task_ajax'),
    path('html/ajax/delete-task/<int:id>', delete_task, name='delete_task'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-todolist-json/', get_todolist_json, name='get_todolist_json'),
    path('json/data-status/<int:id>', status, name='status'),
    path('json/delete/<int:id>', delete_task, name='delete'),
    path('json/', show_json, name='show_json'),
     path('/submit', submit_ajax, name="submit_ajax"),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/views.py
import datetime
from django.urls import reverse
from todolist.models import Task
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers

##fungsi show_todos

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    this_user = request.user
    data_todolist = Task.objects.filter(user=this_user)
    context = {
        'data_todolist': data_todolist,
        'last_login': request.COOKIES['last_login'],
        'name' : this_user
    }
    return render(request, "todolist.html", context)


@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    this_user = request.user
    data_todolist = Task.objects.filter(user=this_user)
    context = {
        'data_todolist': data_todolist,
        'last_login': request.COOKIES['last_login'],
        'name' : this_user
    }
    return render(request, "todolist_ajax.html", context)


def submit_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        
        new_data = Task(user=request.user, title=title, description=description, date=datetime.datetime.now())
        new_data.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()


@login_required(login_url='/todolist/login/')
def show_json(req):
    task_list = Task.objects.filter(user=req.user)
    return HttpResponse(serializers.serialize("json", task_list), content_type="application/json")

def get_todolist_json(request):
    tasks = Task.objects.filter(user = request.user)
    for task in tasks:
        if task.is_finished:
            task.status = 'Done'
        else:
            task.status = 'Not Yet'
    return HttpResponse(serializers.serialize('json', tasks))

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':

        #Title dan Description
        task_title = request.POST['task_title']
        task_description = request.POST['description']

        isFill = False

        #Cek Apakah Title & Description diisi
        if(isinstance(task_title, str) and isinstance(task_description,str)):

            #Panjang 0 berarti kosong
            if (len(task_title.strip()) !=0 and len(task_description.strip()) !=0):
                isFill = True
                task = Task(title=task_title, description=task_description)
                task.user = request.user
                task.save()
                
                return redirect('todolist:show_todolist')

        #Title & Description kosong
        if(isFill == False):
            messages.info(request, 'Please fill both fields with letter(s) or number(s)')

    return render(request,'create_task.html')


# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now().strftime(("%d/%m/%Y %H:%M:%S"))))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def show_todos(request):
    data_todolist = Task.objects.filter(user = request.user)
    context = {'username': request.COOKIES['username'],
               'last_login': request.COOKIES['last_login'],
               'todos': data_todolist,
              }
    return render(request,'todolist_ajax.html', context)


@login_required(login_url='/todolist/login/')
def delete_task(request,id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('todolist:show_todolist')


def status(request,id):
    task = Task.objects.get(id=id)
    task.is_finished= not task.is_finished
    task.save(update_fields=["is_finished"])
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
def delete_task_ajax(request,id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('todolist:show_todolist_ajax')


def status_ajax(request,id):
    task = Task.objects.get(id=id)
    task.is_finished= not task.is_finished
    task.save(update_fields=["is_finished"])
    return redirect('todolist:show_todolist_ajax')

todolist/templates/create_task.html
{% extends 'base.html' %}

 {% block meta %}
 <title>New Task</title>
     <!--INCLUDING BOOTSTRAP-->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 {% endblock meta %}

 {% block content %}

 <style>
    body {
        background-color: #f4f7f6;
        font-family: 'Times New Roman', sans-serif;
        font-weight: 900rem;

    }
    .primary-heading {
        text-align: center;
        font-size: 3rem;
        margin-bottom: 20px;
        margin-top: 30 px;
        font-weight: bold;
        color: rgb(181, 82, 82);

    }
    .separator {
    background-color: #934343;
    }
    .body {
        padding-top: 10px;
        padding: 10px;
    }
    .btn {
        border-radius: 20px;
        border: rgb(149, 68, 68);
        background-color: #a95246;
        padding: 5px 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: medium

    }
    button:hover{
        background-color: #a95246;
    }
    p {
        color: #a4161a;
    }
    input:hover {
        transform: scale(1.01);
        box-shadow: 0 10px 20px #a4161a, 0 4px 8px rgba(90, 74, 94, 0.06);
    }

</style>

 <div class = "new_task">
    <h1 class="primary-heading">📑💓Create A New Task💓📑</h1>
        <div class="separator" style="padding:1px ;" ></div>
            <form method="POST" action="/todolist/create-task/">
                {% csrf_token %}
                <tr>
                    <div class="form-outline mb-4">
                        <td style="text-align: center;color:#d7005d">Title: </td>
                        <td> <input type="text" name="task_title" placeholder="Your task title" class="form-control"></td>
                    </div>                    
                </tr>

                <tr>
                    <div class="form-outline mb-4">
                        <td style="text-align: center;color:#d7005d">Description: </td>
                        <td><textarea name="description" class="form-control" rows="3"></textarea></td>
                    </div>
                    
                </tr>

                <tr>

                    <button class="btn btn-block btn-primary" type="submit">Create</button>
            </form>
            <br>

            <form method="GET" action="/todolist/">
                <button class="btn btn-block btn-primary" type="submit">Cancel</button>
            </form>
        </tr>

        {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}

</div>

 {% endblock content %}

todolist/templates/login.html
<head>
    <title>Login</title>
    <!--INCLUDING BOOTSTRAP-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head>
<style>
    input:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }

    body {
        background-color: #561416;

    }
</style>

<body>
<div class = "card mb-3" style="margin: 80px; margin-top: 150px" >
    <div class="row g-0 d-flex align-items-center">
            <div class="card-body p-5 text-center">
                <h1 class="large fw-bold mb-4 text-uppercase text-center">Login</h1>
                <form method="POST" action="" class="justify-content-center">
                    {% csrf_token %}
                    <div class="form-outline mb-4">
                        <input type="text" id="form2Example1" class="form-control" name="username" placeholder="Username" />
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="form2Example2" class="form-control" name="password" placeholder="Password" />
                    </div>

                    <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
                 
                </form>
    
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        
        </div>
        <div class="col">
            

            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     


            <div class="text-center text-lg-start mt-4 pt-2">
                <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'todolist:register' %}"
                    class="link-danger">Register</a></p>
            </div>
        
        </div>
            

    </div>
</div>

</body>

todolist/templates/register.html
<head>
    <title>Registrasi Akun</title>
    <!--INCLUDING BOOTSTRAP-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
</head>

<style>
    input:hover {
        transform: scale(1.02);
        box-shadow: 0 10px 20px rgba(246, 189, 150, 0.12), 0 4px 8px rgba(132, 40, 40, 0.06);
    }

    body {
        background-color: #7a3a3a;

    }
</style>


<body>
    <div class = "card mb-3" style="margin: 70px; margin-top: 100px" >
        <div class="row g-0 d-flex align-items-center">
            <div class="card" style="border-radius: 1rem;"></div>
                <div class="card-body p-5 text-center">
                    <h1 class="large fw-bold mb-4 text-uppercase text-center">Registration</h1>
    
                    <form method="POST" action="" class="justify-content-center align-top">
                        {% csrf_token %}
                        <table>  
                            {{ form.as_table }}  
                            <tr>  
                                <td></td>
                                <td><input type="submit" name="submit" value="Daftar"/></td>  
                            </tr>  
                        </table> 
                     
                    </form>
        
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            
            </div>
            <div class="col">
                
    
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}     
    
    
                <div class="text-center text-lg-start mt-4 pt-2">
                    <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account? <a href="{% url 'todolist:login' %}"
                        class="link-danger">Login</a></p>
                </div>
            
            </div>
    
        </div>
    </div>
    
</body>

todolist/templates/todolist.html
<head>
  <title>TodoList</title>
  <!--INCLUDING BOOTSTRAP-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<style>

body {
    font-family: 'Helvetica Now', sans-serif;
    font-weight: 800rem;
    background-color: #f4f7f6;
}
.header {
    padding: 10px;
    padding-left: 15px;
    text-align: center;
}
.primary-heading {
    font-size: 4rem;
    font-family: 'Helvetica Now', sans-serif ;
    font-weight: bold;
    color: #8b332e;
    margin-bottom: 8px;
    margin-top: 8px;
}
.batas {
  background-color: #2e4b5f;
}
.body {
    padding-top: 15px;
    padding: 15px;
}

.lastLogin {
    margin-top: 26px;
}
button {
    text-align: center;
    text-decoration: none;
    display: inline-block;
    border-radius: 25px;
    border: rgb(137, 78, 78);
    background-color: #fdfdfc ;
    border: 1px solid #313d3d;
    padding: 5px 15px;

}
button:hover{
    background-color:#eaecef ;
}
a, a:hover {
    color: #205e5e;
    font-size: 13px;
    text-decoration-line: none;
}


h1, h3, h4 {
  font-size: xx-large;
  color: #95733c;
  margin-bottom: 9px;
  margin-top: 9px;

}

h3 {
  font-size: large;
  font-weight: large;
}

h4 {
  font-size: small;
  text-align: right;
  font-weight: small;
}

#desc {
  position: relative;
}
#done {
  font-size: small;
  font-weight:bold;
  color: #a191ca;
  
}

.badge-success {
  background-color: #d0c1de ;
}


.card-header {
  background-color: #fdfdfc;
  vertical-align: middle;
  align-content: center;
  align-items: middle;
  padding-top: 3px;
  padding-bottom: 3px;

  
}
.card-body {
  background-color: #FFC0CB;
  padding-left: 30px;
  padding-bottom: 5px;
}

.card:hover {
    transform: scale(1.01);
    box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
  }
p {
    margin-top: 10px;
    font-size: large;
    color: #006a6a;
    margin-bottom: 10px;
    font-weight: bold;

}


#inprogress {
  font-size: small;
  font-weight: bold;
  color: #b75e5d;
 
}

.badge-warning {
  background-color: #fdecc8 ;
}
.navbar-light .navbar-nav .nav-link {
  color: rgb(204, 0, 0);
}
</style>



<body>
  <div style="align-items: center;"class="wrapper" id="header">
    <div class="header pl-8">
      <div class="d-flex">
        <div class="mr-auto mb-auto mt-auto">
          <h1 class="primary-heading">💌My TodoList✨💫</h1>
        </div>
        <div class="p-4">
          <p>{{ username }}</p></div>
        </div>
      </div>
    </div>
    <div class="batas" style="padding:2px ;" ></div>
    <div class="body">
      {% for data in data_todolist %}
      <div class="card" style="margin-bottom: 15px;" >
        {% if data.is_finished == True%}
          <div class="card-header align-middle mb-auto mt-auto">
              <div class="d-flex align-middle pb-2 pt-2">
                <div class="mr-auto p-0 mb-auto mt-auto"><span class="badge badge-pill badge-success" id="done">Done</span></div>
                <div class="p-1">
                  <h4>Created On: {{ data.date }}</h4>
                </div>
              </div>
          </div>
        {% else %}
          <div class="card-header align-middle pl-4 mb-auto mt-auto ">
            <div class="d-flex align-middle pb-2 pt-2">
              <div class="mr-auto mb-auto mt-auto p-0"><span class="badge badge-pill badge-warning" id="inprogress">In Progress</span></div>
              <div class="p-1">
                <h4>Created On: {{ data.date }}</h4>
              </div>
            </div>
          </div>
        {% endif %}
        <div class="card-body d-flex p-4 pr-2 pl-4" id="card-body">
            <div class="mr-auto justify-content-between" id="desc">
              <h1>{{ data.title }}</h1> <span>{{ data.description }}</span>
            </div>
            <div class="mt-auto align-items-end">
              <button><a href="data-status/{{data.pk}}">Change</a></button>
              <a href="delete-task/{{data.pk}}"><button>🗑️</button></a></td>
            </div>
 
        </div>
      </div>
      {% endfor %}

    
    <button style="margin-top: 16px;"> <a href="create-task/", class="custom-primary-button">Tambah Task</a></button>

    <div class="lastLogin" style="padding-top: 70px;">
        <p style="font-size: small;">Last accessed on {{ last_login }}</p>
        <button style="background-color: #8c1c13;"><a style="color: #f4f7f6;"href="{% url 'todolist:logout' %}", class="custom-alert-button">Logout</a></button>
    </div>

    </div>
  </div>
</body>

todolist/templates/todolist_ajax.html
<head>
    <title>TodoList</title>
    <!--INCLUDING BOOTSTRAP-->
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      </head>
  </head>
  <style>
  
  body {
      font-family: 'Helvetica Now', sans-serif;
      font-weight: 800rem;
      background-color: #f4f7f6;
  }
  .header {
      padding: 10px;
      padding-left: 15px;
      text-align: center;
  }
  .primary-heading {
      font-size: 4rem;
      font-family: 'Helvetica Now', sans-serif ;
      font-weight: bold;
      color: #8b332e;
      margin-bottom: 8px;
      margin-top: 8px;
  }
  .batas {
    background-color: #2e4b5f;
  }
  .body {
      padding-top: 15px;
      padding: 15px;
  }
  
  .lastLogin {
      margin-top: 26px;
  }
  button {
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 25px;
      border: rgb(137, 78, 78);
      background-color: #fdfdfc ;
      border: 1px solid #313d3d;
      padding: 5px 15px;
  
  }
  button:hover{
      background-color:#eaecef ;
  }
  a, a:hover {
      color: #205e5e;
      font-size: 13px;
      text-decoration-line: none;
  }
  
  
  h1, h3, h4 {
    font-size: xx-large;
    color: #95733c;
    margin-bottom: 9px;
    margin-top: 9px;
  
  }
  
  h3 {
    font-size: large;
    font-weight: large;
  }
  
  h4 {
    font-size: small;
    text-align: right;
    font-weight: small;
  }
  
  #desc {
    position: relative;
  }
  #done {
    font-size: small;
    font-weight:bold;
    color: #a191ca;
    
  }
  
  .badge-success {
    background-color: #d0c1de ;
  }
  
  
  .card-header {
    background-color: #fdfdfc;
    vertical-align: middle;
    align-content: center;
    align-items: middle;
    padding-top: 3px;
    padding-bottom: 3px;
  
    
  }
  .card-body {
    background-color: #FFC0CB;
    padding-left: 30px;
    padding-bottom: 5px;
  }
  
  .card:hover {
      transform: scale(1.01);
      box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }
  p {
      margin-top: 10px;
      font-size: large;
      color: #006a6a;
      margin-bottom: 10px;
      font-weight: bold;
  
  }
  
  
  #inprogress {
    font-size: small;
    font-weight: bold;
    color: #b75e5d;
   
  }
  
  .badge-warning {
    background-color: #fdecc8 ;
  }
  .navbar-light .navbar-nav .nav-link {
    color: rgb(204, 0, 0);
  }
  </style>
  
  
  
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
    
    <div style="align-items: center;"class="wrapper" id="header">
      <div class="header pl-8">
        <div class="d-flex">
          <div class="mr-auto mb-auto mt-auto">
            <h1 class="primary-heading">💌My TodoList✨💫</h1>
          </div>
          <div class="p-4">
            <p>{{ username }}</p></div>
          </div>
        </div>
      </div>

      <div class="batas" style="padding:2px ;" ></div>

      <div class="body">
        {% for data in data_todolist %}
        <div class="card" style="margin-bottom: 15px;" >
          {% if data.is_finished == True%}
            <div class="card-header align-middle mb-auto mt-auto">
                <div class="d-flex align-middle pb-2 pt-2">
                  <div class="mr-auto p-0 mb-auto mt-auto"><span class="badge badge-pill badge-success" id="done">Done</span></div>
                  <div class="p-1">
                    <h4>Created On: {{ data.date }}</h4>
                  </div>
                </div>
            </div>
          {% else %}
            <div class="card-header align-middle pl-4 mb-auto mt-auto ">
              <div class="d-flex align-middle pb-2 pt-2">
                <div class="mr-auto mb-auto mt-auto p-0"><span class="badge badge-pill badge-warning" id="inprogress">In Progress</span></div>
                <div class="p-1">
                  <h4>Created On: {{ data.date }}</h4>
                </div>
              </div>
            </div>
          {% endif %}
          <div class="card-body d-flex p-4 pr-2 pl-4" id="card-body">
              <div class="mr-auto justify-content-between" id="desc">
                <h1>{{ data.title }}</h1> <span>{{ data.description }}</span>
              </div>
              <div class="mt-auto align-items-end">
                <button><a href="data-status-ajax/{{data.pk}}">Change</a></button>
                <a href="delete-task-ajax/{{data.pk}}"><button>🗑️</button></a></td>
              </div>
   
          </div>
        </div>
        {% endfor %}
  
      
        <button style="margin-top: 16px;"> <a data-bs-toggle="modal" data-bs-target="#modalAddTask", class="custom-primary-button">Tambah Task</a></button>
  
      <div class="lastLogin" style="padding-top: 70px;">
          <p style="font-size: small;">Last accessed on {{ last_login }}</p>
          <button style="background-color: #8c1c13;"><a style="color: #f4f7f6;"href="{% url 'todolist:logout' %}", class="custom-alert-button">Logout</a></button>
      </div>
  
      </div>

               <!-- BODY -->
               <div class="body">

                <div class="modal" tabindex=-1 id="modalAddTask">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Add Task</h4>
                        </div>
                        <form method="POST" id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="form-outline mb-4">
                                    <input id="title-controller" type="text" name="title" placeholder="Title" required>
                                </div>
                                <div class="form-outline mb-4">
                                    <input id="description-controller" type="text" name="description" placeholder="Description" required>
                                </div>
                            </div>
    
                            <div class="modal-footer">
                                <button type="button" data-bs-dismiss="modal">Close</button>
                                <button id="button" type="submit" style="background-color: #07c5c5;"><a style="color: #f4f7f6;">Save</a></button>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>

        <script>
          async function getTodolist(){
            return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
          }
          async function refreshTodolist(){
            document.getElementById("table").innerHTML=""
            const todolist = await getTodolist()
            let htmlString = `<tr>
              <th>Title</th>
              <th>Description</th>
              <th>Date</th>
            </tr>`
            todolist.forEach((item) => {
              htmlString += `\n<tr>
                <th>${item.fields.title}</th>
                <th>${item.fields.description}</th>
                <th>${item.fields.date}</th>
              </tr>` 
            })
            document.getElementById("table").innerHTML = htmlString
          }
      
          function addTodolist(){
            fetch("{% url 'todolist:submit_ajax' %}", {
              method: "POST",
              body: new FormData(document.querySelector('#form'))
            }).then(refreshTodolist)
            return false
          }
      
          document.getElementById("button").onclick = addTodolist
          refreshTodolist()
        </script>

  </body>
  